Implement weather home screen UI
VitalinaSpinu/Weather pull request #3
Opened 2024-08-14 12:24 UTC by VitalinaSpinu

Implement Weather Home Screen UI

2024-08-15 09:03 UTC, DmitriiVrabie commented on Weather/Assets.xcassets/HomeScreen/Background.imageset/Contents.json
> +      "filename" : "photo-1436891620584-47fd0e565afb 1.png",
use meaningful name

2024-08-15 09:04 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +class WeatherViewModel: ObservableObject {
Extract to separate file

2024-08-15 09:04 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +    }
formatting

2024-08-15 09:04 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +                        print(jsonData)
Print shouldn't go to the main branch, please remove

2024-08-15 09:05 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +struct WeatherDto: Codable {
extract to separate file

2024-08-15 09:05 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +struct Main: Codable {
extract to separate file

2024-08-15 09:06 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +        let units = "metric"
Please use constants for fields that won't be changed

2024-08-15 09:07 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +        AF.request(url, method: .get, parameters: parameters, encoding: URLEncoding.default, headers: nil, interceptor: nil)
Please extract this to separate class to reuse it for other requests

2024-08-15 09:07 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +    @Published var tempMax: String = "-"
Why not blank string but "-"?

2024-08-15 09:08 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +            .response { resp in
We need to show to the user loading while we are fetching weather data

2024-08-15 09:09 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +                    .font(.system(size: 20) .weight(.bold))
Font size could be extracted to constant to reuse

2024-08-15 09:09 UTC, DmitriiVrabie requested changes
Fix commentaries

2024-08-15 10:29 UTC, VitalinaSpinu commented on Weather/ContentView.swift
> +        let units = "metric"
Here everything is constant

2024-08-15 10:37 UTC, VitalinaSpinu commented on Weather/Assets.xcassets/HomeScreen/Background.imageset/Contents.json
> +      "filename" : "photo-1436891620584-47fd0e565afb 1.png",
I did not create this file and I did not give this name. I put the images in the Assets file and then give them meaningful names. Please check!

2024-08-15 10:53 UTC, VitalinaSpinu commented on Weather/ContentView.swift
> +    }
I didn't understand what to do. Please explain to me.

2024-08-15 10:56 UTC, VitalinaSpinu commented on Weather/ContentView.swift
> +            .response { resp in
I'm sorry, but I didn't understand what to do here either. Please explain to me.

2024-08-28 17:31 UTC, DmitriiVrabie commented on Weather/ContentView.swift
> +    var yOffset: CGFloat = 50
Please remove if not used

2024-08-28 17:35 UTC, DmitriiVrabie approved these changes

2024-09-05 09:00 UTC, merged